MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_TAG = 32
MAX_LENGTH_SLUG = 32
MAX_LENGTH_INGREDIENT = 100
MAX_LENGTH_MEASUREMENT_UNIT = 20
MAX_LENGTH_RECIPES = 100

PATTERN_VALID_USERNAME = r'^[\w.@+-]+\Z'
PATTERN_TAG_SLUG = r'^[-a-zA-Z0-9_]+$'

URL_PATH_ME = 'me'
URL_PATH_AVATAR = 'me/avatar'
URL_PATH_SET_PASSWORD = 'set_password'
