MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_TAG = 50
MAX_LENGTH_INGREDIENT = 100
MAX_LENGTH_MEASUREMENT_UNIT = 20
MAX_LENGTH_RECIPES = 100

PATTERN_VALID_USERNAME = r'^[\w.@+-]+\Z'
URL_PATH_ME = 'me'
